name: NVphonography
favicon: null
layout_spectrum: 0.79549
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#D8D0C0'
    - '#183058'
    - '#809060'
    - '#405890'
    - '#E8F0F8'
  brandStrength: 0.012709
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
