analytics: {}
color:
  brandColors:
    - '#D8D0C0'
    - '#183058'
    - '#809060'
    - '#405890'
    - '#E8F0F8'
  brandStrength: 0.012709
  lightness: 0.70498
  rhythmicContrast: 0.317097
  saturation: 0.464738
cta: {}
layout_spectrum: 0.10550380792355807
name: NVphonography
opengraph: {}
purpose: {}
typography_spectrum: 0.6481130919946752
